import { i18n } from 'next-i18next';
export const TOKEN = 'token';
export const AUTH_AB_CRYPT = 'AUTH_AB_CRYPT';
export const LANGUAGES = {
  en: 'English',
  kr: '한국어',
  cn: '繁體中文',
  th: 'ไทย',
};

export const CURRENCIES = {
  tether: 'USD',
  'south-korean-won': 'KRW',
  'chinese-yuan-renminbi': 'CNY',
};

export const CURRENCIES_SYMBOL = {
  tether: '$',
  'south-korean-won': '₩',
  'chinese-yuan-renminbi': '￥',
};

export const DEFAULT_RESPONSE = {
  docs: [],
  totalDocs: 0,
  limit: 15,
  page: 1,
  totalPages: 1,
};

export const DEFAULT_FILTER = {
  filter: {},
  token: '',
  timeRange: '',
  page: 1,
  limit: 20,
  sort: {
    createdAt: -1,
  },
};

export const TRANSACTION_STATUS = {
  PROCESSING: {
    text: 'Processing',
    color: 'orange',
  },
  COMPLETED: {
    text: 'Completed',
    color: 'green',
  },
  ERROR: {
    text: 'Error',
    color: 'red',
  },
  CANCELED_BY_ADMIN: {
    text: 'Rejected',
    color: 'red',
  },
};

export const NAMESPACE_GLOBAL = [
  'header',
  'footer',
  'common',
  'error_message',
  'success_message',
];

export const KYC_STATUS = {
  SUBMITTED: 'submitted',
  VERIFIED: 'confirmed',
  REJECTED: 'rejected',
};

export const EN_PHONE_CODE = [
  { country: 'Korea', code: 82 },
  { country: 'Vietnam', code: 84 },
  { country: 'Canada', code: 1 },
  { country: 'China', code: 86 },
  { country: 'Afghanistan', code: 93 },
  { country: 'Albania', code: 355 },
  { country: 'Algeria', code: 213 },
  { country: 'Andorra', code: 376 },
  { country: 'Angola', code: 244 },
  { country: 'Antigua and Barbuda', code: 1268 },
  { country: 'Argentina', code: 54 },
  { country: 'Armenia', code: 374 },
  { country: 'Australia', code: 61 },
  { country: 'Austria', code: 43 },
  { country: 'Azerbaijan', code: 994 },
  { country: 'Bahrain', code: 973 },
  { country: 'Bangladesh', code: 880 },
  { country: 'Barbados', code: 1246 },
  { country: 'Belarus', code: 375 },
  { country: 'Belgium', code: 32 },
  { country: 'Belize', code: 501 },
  { country: 'Benin', code: 229 },
  { country: 'Bhutan', code: 975 },
  { country: 'Bolivia', code: 591 },
  { country: 'Bosnia', code: 387 },
  { country: 'Botswana', code: 267 },
  { country: 'Brazil', code: 55 },
  { country: 'Brunei', code: 673 },
  { country: 'Bulgaria', code: 359 },
  { country: 'Burkina Faso', code: 226 },
  { country: 'Burundi', code: 257 },
  { country: 'Cambodia', code: 855 },
  { country: 'Cameroon', code: 237 },
  { country: 'Cape', code: 238 },
  { country: 'Catalonia', code: 3497 },
  { country: 'Central Africa', code: 236 },
  { country: 'Chad', code: 235 },
  { country: 'Chile', code: 56 },
  { country: 'Colombia', code: 57 },
  { country: 'Comoros', code: 269 },
  { country: 'Congo', code: 242 },
  { country: 'Congo', code: 243 },
  { country: 'Cook Islands', code: 682 },
  { country: 'Costa Rica', code: 506 },
  { country: "Cote D'Ivoire", code: 225 },
  { country: 'Croatia', code: 385 },
  { country: 'Cuba', code: 53 },
  { country: 'Cyprus', code: 357 },
  { country: 'Czech', code: 420 },
  { country: 'Denmark', code: 45 },
  { country: 'Djibouti', code: 253 },
  { country: 'Dominica', code: 1767 },
  { country: 'Dominican Republic', code: 1849 },
  { country: 'Ecuador', code: 593 },
  { country: 'Egypt', code: 20 },
  { country: 'El Salvador', code: 503 },
  { country: 'Equatorial Guinea', code: 240 },
  { country: 'Eritrea', code: 291 },
  { country: 'Estonia', code: 372 },
  { country: 'Ethiopia', code: 251 },
  { country: 'Fiji', code: 679 },
  { country: 'Finland', code: 358 },
  { country: 'France', code: 33 },
  { country: 'Gabon', code: 241 },
  { country: 'Gambia', code: 220 },
  { country: 'Georgia', code: 995 },
  { country: 'Germany', code: 49 },
  { country: 'Ghana', code: 233 },
  { country: 'Greece', code: 30 },
  { country: 'Grenada', code: 1476 },
  { country: 'Guatemala', code: 590 },
  { country: 'Guinea', code: 224 },
  { country: 'Guinea-Bissau', code: 245 },
  { country: 'Guyana', code: 592 },
  { country: 'HongKong', code: 852 },
  { country: 'Haiti', code: 509 },
  { country: 'Honduras', code: 504 },
  { country: 'Hungary', code: 36 },
  { country: 'Iceland', code: 354 },
  { country: 'India', code: 91 },
  { country: 'Indonesia', code: 62 },
  { country: 'Iran', code: 98 },
  { country: 'Iraq', code: 964 },
  { country: 'Ireland', code: 353 },
  { country: 'Israel', code: 972 },
  { country: 'Italy', code: 39 },
  { country: 'Jamaica', code: 1876 },
  { country: 'Japan', code: 81 },
  { country: 'Jordan', code: 962 },
  { country: 'Kazakhstan', code: 327 },
  { country: 'Kenya', code: 254 },
  { country: 'Kiribati', code: 686 },
  { country: 'Kosovo', code: 383 },
  { country: 'Kuwait', code: 965 },
  { country: 'Kyrgyzstan', code: 996 },
  { country: 'Laos', code: 856 },
  { country: 'Latvia', code: 371 },
  { country: 'Lebanon', code: 961 },
  { country: 'Lesotho', code: 266 },
  { country: 'Liberia', code: 231 },
  { country: 'Libya', code: 218 },
  { country: 'Liechtenstein', code: 423 },
  { country: 'Lithuania', code: 370 },
  { country: 'Luxembourg', code: 352 },
  { country: 'Macedonia', code: 289 },
  { country: 'Madagascar', code: 261 },
  { country: 'Malawi', code: 265 },
  { country: 'Malaysia', code: 60 },
  { country: 'Maldives', code: 960 },
  { country: 'Mali', code: 223 },
  { country: 'Malta', code: 356 },
  { country: 'Marshall', code: 692 },
  { country: 'Mauritania', code: 222 },
  { country: 'Mauritius', code: 230 },
  { country: 'Mexico', code: 52 },
  { country: 'Micronesia', code: 691 },
  { country: 'Moldova', code: 373 },
  { country: 'Monaco', code: 377 },
  { country: 'Mongolia', code: 976 },
  { country: 'Montenegro', code: 382 },
  { country: 'Morocco', code: 212 },
  { country: 'Mozambique', code: 258 },
  { country: 'Myanmar', code: 95 },
  { country: 'Nagorno', code: 37447 },
  { country: 'Namibia', code: 264 },
  { country: 'Nauru', code: 674 },
  { country: 'Nepal', code: 977 },
  { country: 'Netherlands', code: 31 },
  { country: 'New Zealand', code: 64 },
  { country: 'Nicaragua', code: 505 },
  { country: 'Niger', code: 227 },
  { country: 'Nigeria', code: 234 },
  { country: 'Niue', code: 683 },
  { country: 'Northern Cyprus', code: 392 },
  { country: 'Norway', code: 47 },
  { country: 'Oman', code: 968 },
  { country: 'Pakistan', code: 92 },
  { country: 'Palau', code: 680 },
  { country: 'Palestine', code: 970 },
  { country: 'Panama', code: 507 },
  { country: 'Papua New Guinea', code: 675 },
  { country: 'Paraguay', code: 595 },
  { country: 'North Korea', code: 850 },
  { country: 'Peru', code: 51 },
  { country: 'Philippines', code: 63 },
  { country: 'Poland', code: 48 },
  { country: 'Portugal', code: 351 },
  { country: 'Qatar', code: 974 },
  { country: 'Romania', code: 40 },
  { country: 'Russia', code: 7 },
  { country: 'Rwanda', code: 250 },
  { country: 'Saint Kitts and Nevis', code: 1869 },
  { country: 'Saint Lucia', code: 1758 },
  { country: 'Saint Vincent and the Grenadines', code: 1784 },
  { country: 'Samoa', code: 685 },
  { country: 'San Marino', code: 378 },
  { country: 'Sao Tome and Principe', code: 239 },
  { country: 'Saudi Arabia', code: 966 },
  { country: 'Senegal', code: 221 },
  { country: 'Serbia', code: 381 },
  { country: 'Seychelles', code: 248 },
  { country: 'Sierra Leone', code: 232 },
  { country: 'Singapore', code: 65 },
  { country: 'Slovakia', code: 421 },
  { country: 'Slovenia', code: 386 },
  { country: 'Solomon', code: 677 },
  { country: 'Somalia', code: 252 },
  { country: 'South Africa', code: 27 },
  { country: 'South Sudan', code: 211 },
  { country: 'Spain', code: 34 },
  { country: 'Sri Lanka', code: 94 },
  { country: 'Sudan', code: 249 },
  { country: 'Suriname', code: 597 },
  { country: 'Swaziland', code: 268 },
  { country: 'Sweden', code: 46 },
  { country: 'Switzerland', code: 41 },
  { country: 'Syria', code: 963 },
  { country: 'Taiwan', code: 886 },
  { country: 'Tajikistan', code: 996 },
  { country: 'Tanzania', code: 255 },
  { country: 'Thailand', code: 66 },
  { country: 'Timor-Leste', code: 670 },
  { country: 'Togo', code: 228 },
  { country: 'Tonga', code: 676 },
  { country: 'Trinidad and Tobago', code: 1868 },
  { country: 'Tunisia', code: 216 },
  { country: 'Turkey', code: 90 },
  { country: 'Turkmenistan', code: 993 },
  { country: 'Tuvalu', code: 688 },
  { country: 'Uganda', code: 256 },
  { country: 'Ukraine', code: 380 },
  { country: 'United Arab Emirates', code: 971 },
  { country: 'United Kingdom', code: 44 },
  { country: 'United States', code: 1 },
  { country: 'Uruguay', code: 598 },
  { country: 'Uzbekistan', code: 998 },
  { country: 'Vanuatu', code: 678 },
  { country: 'Vatican', code: 379 },
  { country: 'Venezuela', code: 58 },
  { country: 'Western Sahara', code: 210 },
  { country: 'Yemen', code: 967 },
  { country: 'Zambia', code: 260 },
  { country: 'Zimbabwe', code: 263 },
  { country: 'Macao', code: 853 },
];
export const KR_PHONE_CODE = [
  { country: '한국', code: 82 },
  { country: '베트남', code: 84 },
  { country: '캐나다', code: 1 },
  { country: '중국', code: 86 },
  { country: '아프가니스탄', code: 93 },
  { country: '알바니아', code: 355 },
  { country: '알제리', code: 213 },
  { country: '안도라', code: 376 },
  { country: '앙골라', code: 244 },
  { country: '앤티가 바부다', code: 1268 },
  { country: '아르헨티나', code: 54 },
  { country: '아르메니아', code: 374 },
  { country: '호주', code: 61 },
  { country: '오스트리아', code: 43 },
  { country: '아제르바이잔', code: 994 },
  { country: '바레인', code: 973 },
  { country: '방글라데시', code: 880 },
  { country: '바베이도스', code: 1246 },
  { country: '벨라루스', code: 375 },
  { country: '벨기에', code: 32 },
  { country: '벨리즈', code: 501 },
  { country: '베냉', code: 229 },
  { country: '부탄', code: 975 },
  { country: '볼리비아', code: 591 },
  { country: '보스니아 헤르체고비나', code: 387 },
  { country: '보츠와나', code: 267 },
  { country: '브라질', code: 55 },
  { country: '브루나이 다루살람', code: 673 },
  { country: '불가리아', code: 359 },
  { country: '부키 나 파소', code: 226 },
  { country: '부룬디', code: 257 },
  { country: '캄보디아', code: 855 },
  { country: '카메룬', code: 237 },
  { country: '카보베르데', code: 238 },
  { country: '카탈로니아', code: 3497 },
  { country: '중앙 아프리카 공화국', code: 236 },
  { country: '차드', code: 235 },
  { country: '칠레', code: 56 },
  { country: '콜롬비아', code: 57 },
  { country: '코모로', code: 269 },
  { country: '콩고', code: 242 },
  { country: '콩고 민주 공화국', code: 243 },
  { country: '쿡 제도', code: 682 },
  { country: '코스타리카', code: 506 },
  { country: '코트디부아르', code: 225 },
  { country: '크로아티아', code: 385 },
  { country: '쿠바', code: 53 },
  { country: '키프로스', code: 357 },
  { country: '체코', code: 420 },
  { country: '덴마크', code: 45 },
  { country: '지부티', code: 253 },
  { country: '도미니카', code: 1767 },
  { country: '도미니카 공화국', code: 1849 },
  { country: '에콰도르', code: 593 },
  { country: '이집트', code: 20 },
  { country: '엘살바도르', code: 503 },
  { country: '적도 기니', code: 240 },
  { country: '에리트레아', code: 291 },
  { country: '에스토니아', code: 372 },
  { country: '에티오피아', code: 251 },
  { country: '피지', code: 679 },
  { country: '핀란드', code: 358 },
  { country: '프랑스', code: 33 },
  { country: '가봉', code: 241 },
  { country: '감비아', code: 220 },
  { country: '조르지아', code: 995 },
  { country: '독일', code: 49 },
  { country: '가나', code: 233 },
  { country: '그리스', code: 30 },
  { country: '그레나다', code: 1476 },
  { country: '과테말라', code: 590 },
  { country: '기니', code: 224 },
  { country: '기니비사우', code: 245 },
  { country: '가이아나', code: 592 },
  { country: '홍콩', code: 852 },
  { country: '아이티', code: 509 },
  { country: '온두라스', code: 504 },
  { country: '헝가리', code: 36 },
  { country: '아이슬란드', code: 354 },
  { country: '인도', code: 91 },
  { country: '인도네시아', code: 62 },
  { country: '이란', code: 98 },
  { country: '이라크', code: 964 },
  { country: '아일랜드', code: 353 },
  { country: '이스라엘', code: 972 },
  { country: '이탈리아', code: 39 },
  { country: '자메이카', code: 1876 },
  { country: '일본', code: 81 },
  { country: '요르단', code: 962 },
  { country: '카자흐스탄', code: 327 },
  { country: '케냐', code: 254 },
  { country: '키리바시', code: 686 },
  { country: '코소보', code: 383 },
  { country: '쿠웨이트', code: 965 },
  { country: '키르기스스탄', code: 996 },
  { country: '라오스', code: 856 },
  { country: '라트비아', code: 371 },
  { country: '레바논', code: 961 },
  { country: '레소토', code: 266 },
  { country: '라이베리아', code: 231 },
  { country: '리비아', code: 218 },
  { country: '리히텐슈타인', code: 423 },
  { country: '리투아니아', code: 370 },
  { country: '룩셈부르크', code: 352 },
  { country: '마케도니아', code: 289 },
  { country: '마다가스카르', code: 261 },
  { country: '말라위', code: 265 },
  { country: '말레이시아', code: 60 },
  { country: '몰디브', code: 960 },
  { country: '말리', code: 223 },
  { country: '몰타', code: 356 },
  { country: '마셜 제도', code: 692 },
  { country: '모리타니', code: 222 },
  { country: '모리셔스', code: 230 },
  { country: '멕시코', code: 52 },
  { country: '미크로네시아', code: 691 },
  { country: '몰도바', code: 373 },
  { country: '모나코', code: 377 },
  { country: '몽골리아', code: 976 },
  { country: '몬테네그로', code: 382 },
  { country: '모로코', code: 212 },
  { country: '모잠비크', code: 258 },
  { country: '미얀마', code: 95 },
  { country: '나고르노', code: 37447 },
  { country: '나미비아', code: 264 },
  { country: '나우루', code: 674 },
  { country: '네팔', code: 977 },
  { country: '네덜란드', code: 31 },
  { country: 'New Zealand', code: 64 },
  { country: '니카라과', code: 505 },
  { country: '니제르', code: 227 },
  { country: '나이지리아', code: 234 },
  { country: '니우에', code: 683 },
  { country: '북부 키프로스', code: 392 },
  { country: '노르웨이', code: 47 },
  { country: '오만', code: 968 },
  { country: '파키스탄', code: 92 },
  { country: '팔라우', code: 680 },
  { country: '팔레스타인', code: 970 },
  { country: '파나마', code: 507 },
  { country: '파푸아 뉴기니', code: 675 },
  { country: '파라과이', code: 595 },
  { country: '북한', code: 850 },
  { country: '페루', code: 51 },
  { country: '필리핀', code: 63 },
  { country: '폴란드', code: 48 },
  { country: '포르투갈', code: 351 },
  { country: '카타르', code: 974 },
  { country: '루마니아', code: 40 },
  { country: '러시아', code: 7 },
  { country: '르완다', code: 250 },
  { country: '세인트 키츠 네비스', code: 1869 },
  { country: '세인트루시아', code: 1758 },
  { country: '세인트 빈센트 그레나딘', code: 1784 },
  { country: '사모아', code: 685 },
  { country: '산 마리노', code: 378 },
  { country: '상투메 프린시페', code: 239 },
  { country: '사우디 아라비아', code: 966 },
  { country: '세네갈', code: 221 },
  { country: '세르비아', code: 381 },
  { country: '세이셸', code: 248 },
  { country: '시에라리온', code: 232 },
  { country: '싱가포르', code: 65 },
  { country: '슬로바키아', code: 421 },
  { country: '슬로베니아', code: 386 },
  { country: '솔로몬 제도', code: 677 },
  { country: '소말리아', code: 252 },
  { country: '남아프리카', code: 27 },
  { country: '남 수단', code: 211 },
  { country: '스페인', code: 34 },
  { country: '스리랑카', code: 94 },
  { country: '수단', code: 249 },
  { country: '수리남', code: 597 },
  { country: '스와질랜드', code: 268 },
  { country: '스웨덴', code: 46 },
  { country: '스위스', code: 41 },
  { country: '시리아', code: 963 },
  { country: '대만', code: 886 },
  { country: '타지키스탄', code: 996 },
  { country: '탄자니아', code: 255 },
  { country: '태국', code: 66 },
  { country: '동티모르', code: 670 },
  { country: '토고', code: 228 },
  { country: '통가', code: 676 },
  { country: '트리니다드토바고', code: 1868 },
  { country: '튀니지', code: 216 },
  { country: '터키', code: 90 },
  { country: '투르크메니스탄', code: 993 },
  { country: '투발루', code: 688 },
  { country: '우간다', code: 256 },
  { country: '우크라이나', code: 380 },
  { country: '아랍 에미리트', code: 971 },
  { country: '영국', code: 44 },
  { country: '미국', code: 1 },
  { country: '우루과이', code: 598 },
  { country: '우즈베키스탄', code: 998 },
  { country: '바누아투', code: 678 },
  { country: '바티칸', code: 379 },
  { country: '베네수엘라', code: 58 },
  { country: '서부 사하라', code: 210 },
  { country: '예멘', code: 967 },
  { country: '잠비아', code: 260 },
  { country: '짐바브웨', code: 263 },
  { country: '짐바브웨', code: 853 },
];

export const CN_PHONE_CODE = [
  { country: '大韩民国', code: 82 },
  { country: '越南', code: 84 },
  { country: '加拿大', code: 1 },
  { country: '中国', code: 86 },
  { country: '阿富汗', code: 93 },
  { country: '阿尔巴尼亚', code: 355 },
  { country: '阿尔及利亚', code: 213 },
  { country: '安道尔', code: 376 },
  { country: '安哥拉', code: 244 },
  { country: '安圭拉', code: 1268 },
  { country: '阿根廷', code: 54 },
  { country: '亚美尼亚', code: 374 },
  { country: '澳大利亚', code: 61 },
  { country: '奥地利', code: 43 },
  { country: '阿塞拜疆', code: 994 },
  { country: '巴林', code: 973 },
  { country: '孟加拉国', code: 880 },
  { country: '巴巴多斯', code: 1246 },
  { country: '白俄罗斯', code: 375 },
  { country: '比利时', code: 32 },
  { country: '伯利兹', code: 501 },
  { country: '贝宁', code: 229 },
  { country: '不丹', code: 975 },
  { country: '玻利维亚', code: 591 },
  { country: '波斯尼亚和黑塞哥维那', code: 387 },
  { country: '博茨瓦纳', code: 267 },
  { country: '巴西', code: 55 },
  { country: '文莱达鲁萨兰国', code: 673 },
  { country: '保加利亚', code: 359 },
  { country: '布基纳法索', code: 226 },
  { country: '布隆迪', code: 257 },
  { country: '柬埔寨', code: 855 },
  { country: '喀麦隆', code: 237 },
  { country: '佛得角', code: 238 },
  { country: '카탈로니아', code: 3497 },
  { country: '中非共和国', code: 236 },
  { country: '乍得', code: 235 },
  { country: '智利', code: 56 },
  { country: '哥伦比亚', code: 57 },
  { country: '科摩罗', code: 269 },
  { country: '刚果', code: 242 },
  { country: '刚果民主共和国', code: 243 },
  { country: '库克群岛', code: 682 },
  { country: '哥斯达黎加', code: 506 },
  { country: '科特迪瓦', code: 225 },
  { country: '克罗地亚', code: 385 },
  { country: '古巴', code: 53 },
  { country: '塞浦路斯', code: 357 },
  { country: '捷克共和国', code: 420 },
  { country: '丹麦', code: 45 },
  { country: '吉布提', code: 253 },
  { country: '多米尼克', code: 1767 },
  { country: '多明尼加共和国', code: 1849 },
  { country: '厄瓜多尔', code: 593 },
  { country: '埃及', code: 20 },
  { country: '萨尔瓦多', code: 503 },
  { country: '赤道几内亚', code: 240 },
  { country: '厄立特里亚', code: 291 },
  { country: '爱沙尼亚', code: 372 },
  { country: '埃塞俄比亚', code: 251 },
  { country: '斐济', code: 679 },
  { country: '芬兰', code: 358 },
  { country: '法国', code: 33 },
  { country: '加蓬', code: 241 },
  { country: '冈比亚', code: 220 },
  { country: '乔治亚州', code: 995 },
  { country: '德国', code: 49 },
  { country: '加纳', code: 233 },
  { country: '希腊', code: 30 },
  { country: '格林纳达', code: 1476 },
  { country: '危地马拉', code: 590 },
  { country: '几内亚', code: 224 },
  { country: '几内亚比绍', code: 245 },
  { country: '圭亚那', code: 592 },
  { country: '香港', code: 852 },
  { country: '海地', code: 509 },
  { country: '洪都拉斯', code: 504 },
  { country: '匈牙利', code: 36 },
  { country: '冰岛', code: 354 },
  { country: '印度', code: 91 },
  { country: '印度尼西亚', code: 62 },
  { country: '伊朗', code: 98 },
  { country: '伊拉克', code: 964 },
  { country: '爱尔兰', code: 353 },
  { country: '以色列', code: 972 },
  { country: '意大利', code: 39 },
  { country: '牙买加', code: 1876 },
  { country: '日本', code: 81 },
  { country: '约旦', code: 962 },
  { country: '哈萨克斯坦', code: 327 },
  { country: '肯尼亚', code: 254 },
  { country: '基里巴斯', code: 686 },
  { country: '科索沃', code: 383 },
  { country: '科威特', code: 965 },
  { country: '吉尔吉斯斯坦', code: 996 },
  { country: '老挝人民民主共和国', code: 856 },
  { country: '拉脱维亚', code: 371 },
  { country: '黎巴嫩', code: 961 },
  { country: '莱索托', code: 266 },
  { country: '利比里亚', code: 231 },
  { country: '利比亚', code: 218 },
  { country: '列支敦士登', code: 423 },
  { country: '立陶宛', code: 370 },
  { country: '卢森堡', code: 352 },
  { country: '马其顿', code: 289 },
  { country: '马达加斯加', code: 261 },
  { country: '马拉维', code: 265 },
  { country: '马来西亚', code: 60 },
  { country: '马尔代夫', code: 960 },
  { country: '马里', code: 223 },
  { country: '马耳他', code: 356 },
  { country: '马绍尔群岛', code: 692 },
  { country: '毛里塔尼亚', code: 222 },
  { country: '毛里求斯', code: 230 },
  { country: '墨西哥', code: 52 },
  { country: '密克罗尼西亚', code: 691 },
  { country: '摩尔多瓦', code: 373 },
  { country: '摩纳哥', code: 377 },
  { country: '蒙古', code: 976 },
  { country: '黑山', code: 382 },
  { country: '摩洛哥', code: 212 },
  { country: '莫桑比克', code: 258 },
  { country: '缅甸', code: 95 },
  { country: '纳戈尔诺', code: 37447 },
  { country: '纳米比亚', code: 264 },
  { country: '瑙鲁', code: 674 },
  { country: '尼泊尔', code: 977 },
  { country: '荷兰', code: 31 },
  { country: '新西兰', code: 64 },
  { country: '尼加拉瓜', code: 505 },
  { country: '尼日尔', code: 227 },
  { country: '尼日利亚', code: 234 },
  { country: '纽埃', code: 683 },
  { country: '北塞浦路斯', code: 392 },
  { country: '挪威', code: 47 },
  { country: '阿曼', code: 968 },
  { country: '巴基斯坦', code: 92 },
  { country: '帕劳', code: 680 },
  { country: '巴勒斯坦', code: 970 },
  { country: '巴拿马', code: 507 },
  { country: '巴布亚新几内亚', code: 675 },
  { country: '巴拉圭', code: 595 },
  { country: '北朝鲜', code: 850 },
  { country: '秘鲁', code: 51 },
  { country: '菲律宾', code: 63 },
  { country: '波兰', code: 48 },
  { country: '葡萄牙', code: 351 },
  { country: '卡塔尔', code: 974 },
  { country: '罗马尼亚', code: 40 },
  { country: '俄罗斯', code: 7 },
  { country: '卢旺达', code: 250 },
  { country: '圣基茨和尼维斯', code: 1869 },
  { country: '圣卢西亚', code: 1758 },
  { country: '圣文森特和格林纳丁斯', code: 1784 },
  { country: '萨摩亚', code: 685 },
  { country: '圣马力诺', code: 378 },
  { country: '圣多美和普林西比', code: 239 },
  { country: '沙特阿拉伯', code: 966 },
  { country: '塞内加尔', code: 221 },
  { country: '塞尔维亚', code: 381 },
  { country: '塞舌尔', code: 248 },
  { country: '塞拉利昂', code: 232 },
  { country: '新加坡', code: 65 },
  { country: '斯洛伐克', code: 421 },
  { country: '斯洛文尼亚', code: 386 },
  { country: '所罗门群岛', code: 677 },
  { country: '索马里', code: 252 },
  { country: '南非', code: 27 },
  { country: '南苏丹', code: 211 },
  { country: '西班牙', code: 34 },
  { country: '斯里兰卡', code: 94 },
  { country: '苏丹', code: 249 },
  { country: '苏里南', code: 597 },
  { country: '斯威士兰', code: 268 },
  { country: '瑞典', code: 46 },
  { country: '瑞士', code: 41 },
  { country: '叙利亚', code: 963 },
  { country: '台湾', code: 886 },
  { country: '塔吉克斯坦', code: 996 },
  { country: '坦桑尼亚', code: 255 },
  { country: '泰国', code: 66 },
  { country: '东帝汶', code: 670 },
  { country: '多哥', code: 228 },
  { country: '汤加', code: 676 },
  { country: '特立尼达和多巴哥', code: 1868 },
  { country: '突尼斯', code: 216 },
  { country: '土耳其', code: 90 },
  { country: '土库曼斯坦', code: 993 },
  { country: '图瓦卢', code: 688 },
  { country: '乌干达', code: 256 },
  { country: '乌克兰', code: 380 },
  { country: '阿拉伯联合酋长国', code: 971 },
  { country: '英国', code: 44 },
  { country: '美国', code: 1 },
  { country: '乌拉圭', code: 598 },
  { country: '乌兹别克斯坦', code: 998 },
  { country: '瓦努阿图', code: 678 },
  { country: '教廷', code: 379 },
  { country: '委内瑞拉', code: 58 },
  { country: '撒哈拉沙漠西部a', code: 210 },
  { country: '也门', code: 967 },
  { country: '赞比亚', code: 260 },
  { country: '津巴布韦', code: 263 },
  { country: '澳门', code: 853 },
];

export const EN_COUNTRY_LIST = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'land Islands', code: 'AX' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'Andorra', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, The Democratic Republic of the', code: 'CD' },
  { name: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: "Cote D'Ivoire", code: 'CI' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  { name: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Greece', code: 'GR' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  { name: 'Holy See (Vatican City State)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran, Islamic Republic Of', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', code: 'IM' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: "Korea, Democratic People'S Republic of", code: 'KP' },
  { name: 'Korea, Republic of', code: 'KR' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: "Lao, People's Democratic Republic", code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia, Federated States of', code: 'FM' },
  { name: 'Moldova, Republic of', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montenegro', code: 'ME' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Netherlands Antilles', code: 'AN' },
  { name: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', code: 'NF' },
  { name: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestinian Territory, Occupied', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', code: 'PN' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Reunion', code: 'RE' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russian Federation', code: 'RU' },
  { name: 'Rwanda', code: 'RW' },
  { name: 'Saint Helena', code: 'SH' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia', code: 'RS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan, Province of China', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands, British', code: 'VG' },
  { name: 'Virgin Islands, U.S.', code: 'VI' },
  { name: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];

export const KR_COUNTRY_LIST = [
  { name: '아프가니스탄', code: 'AF' },
  { name: '올란드 제도', code: 'AX' },
  { name: '알바니아', code: 'AL' },
  { name: '알제리', code: 'DZ' },
  { name: '아메리칸 사모아', code: 'AS' },
  { name: '안도라', code: 'AD' },
  { name: '앙골라', code: 'AO' },
  { name: '앵귈라', code: 'AI' },
  { name: '남극', code: 'AQ' },
  { name: '앤티가 바부다', code: 'AG' },
  { name: '아르헨티나', code: 'AR' },
  { name: '아르메니아', code: 'AM' },
  { name: '아루바', code: 'AW' },
  { name: '호주', code: 'AU' },
  { name: '오스트리아', code: 'AT' },
  { name: '아제르바이잔', code: 'AZ' },
  { name: '바하마', code: 'BS' },
  { name: '바레인', code: 'BH' },
  { name: '방글라데시', code: 'BD' },
  { name: '바베이도스', code: 'BB' },
  { name: '벨라루스', code: 'BY' },
  { name: '벨기에', code: 'BE' },
  { name: '벨리즈', code: 'BZ' },
  { name: '베냉', code: 'BJ' },
  { name: '버뮤다', code: 'BM' },
  { name: '부탄', code: 'BT' },
  { name: '볼리비아', code: 'BO' },
  { name: '보스니아 헤르체고비나', code: 'BA' },
  { name: '보츠와나', code: 'BW' },
  { name: '부베 아일랜드', code: 'BV' },
  { name: '브라질', code: 'BR' },
  { name: '영국령 인도양 영토', code: 'IO' },
  { name: '文莱达鲁萨兰国', code: 'BN' },
  { name: '불가리아', code: 'BG' },
  { name: '부키 나 파소', code: 'BF' },
  { name: '부룬디', code: 'BI' },
  { name: '캄보디아', code: 'KH' },
  { name: '카메룬', code: 'CM' },
  { name: '캐나다', code: 'CA' },
  { name: '카보베르데', code: 'CV' },
  { name: '케이맨 제도', code: 'KY' },
  { name: '중앙 아프리카 공화국', code: 'CF' },
  { name: '차드', code: 'TD' },
  { name: '칠레', code: 'CL' },
  { name: '중국', code: 'CN' },
  { name: '크리스마스 아일랜드', code: 'CX' },
  { name: '코코스(킬링) 제도', code: 'CC' },
  { name: '콜롬비아', code: 'CO' },
  { name: '코모로', code: 'KM' },
  { name: '콩고', code: 'CG' },
  { name: '콩고 민주 공화국', code: 'CD' },
  { name: '쿡 제도', code: 'CK' },
  { name: '코스타리카', code: 'CR' },
  { name: '코트디부아르', code: 'CI' },
  { name: '크로아티아', code: 'HR' },
  { name: '쿠바', code: 'CU' },
  { name: '키프로스', code: 'CY' },
  { name: '체코 공화국', code: 'CZ' },
  { name: '덴마크', code: 'DK' },
  { name: '지부티', code: 'DJ' },
  { name: '도미니카', code: 'DM' },
  { name: '도미니카 공화국', code: 'DO' },
  { name: '에콰도르', code: 'EC' },
  { name: '이집트', code: 'EG' },
  { name: '엘살바도르', code: 'SV' },
  { name: '적도 기니', code: 'GQ' },
  { name: '에리트레아', code: 'ER' },
  { name: '에스토니아', code: 'EE' },
  { name: '에티오피아', code: 'ET' },
  { name: '포클랜드 제도(말비나스)', code: 'FK' },
  { name: '페로 제도', code: 'FO' },
  { name: '피지', code: 'FJ' },
  { name: '핀란드', code: 'FI' },
  { name: '프랑스', code: 'FR' },
  { name: '프랑스령 기아나', code: 'GF' },
  { name: '프랑스 령 폴리네시아의', code: 'PF' },
  { name: '프랑스 남부 지역', code: 'TF' },
  { name: '가봉', code: 'GA' },
  { name: '감비아', code: 'GM' },
  { name: '조르지아', code: 'GE' },
  { name: '독일', code: 'DE' },
  { name: '가나', code: 'GH' },
  { name: '지브롤터', code: 'GI' },
  { name: '그리스', code: 'GR' },
  { name: '그린란드', code: 'GL' },
  { name: '그레나다', code: 'GD' },
  { name: '과들루프', code: 'GP' },
  { name: '괌', code: 'GU' },
  { name: '과테말라', code: 'GT' },
  { name: '건지', code: 'GG' },
  { name: '기니', code: 'GN' },
  { name: '기니비사우', code: 'GW' },
  { name: '가이아나', code: 'GY' },
  { name: '아이티', code: 'HT' },
  { name: '허드 아일랜드와 맥도날드 제도', code: 'HM' },
  { name: '교황청(바티칸 시국)', code: 'VA' },
  { name: '온두라스', code: 'HN' },
  { name: '홍콩', code: 'HK' },
  { name: '헝가리', code: 'HU' },
  { name: '아이슬란드', code: 'IS' },
  { name: '인도', code: 'IN' },
  { name: '인도네시아', code: 'ID' },
  { name: '이란', code: 'IR' },
  { name: '이라크', code: 'IQ' },
  { name: '아일랜드', code: 'IE' },
  { name: '맨 섬', code: 'IM' },
  { name: '이스라엘', code: 'IL' },
  { name: '이탈리아', code: 'IT' },
  { name: '자메이카', code: 'JM' },
  { name: '일본', code: 'JP' },
  { name: '저지', code: 'JE' },
  { name: '요르단', code: 'JO' },
  { name: '카자흐스탄', code: 'KZ' },
  { name: '케냐', code: 'KE' },
  { name: '키리바시', code: 'KI' },
  { name: '조선민주주의인민공화국', code: 'KP' },
  { name: '대한민국', code: 'KR' },
  { name: '쿠웨이트', code: 'KW' },
  { name: '키르기스스탄', code: 'KG' },
  { name: '라오스 인민 민주 공화국', code: 'LA' },
  { name: '라트비아', code: 'LV' },
  { name: '레바논', code: 'LB' },
  { name: '레소토', code: 'LS' },
  { name: '라이베리아', code: 'LR' },
  { name: '리비아', code: 'LY' },
  { name: '리히텐슈타인', code: 'LI' },
  { name: '리투아니아', code: 'LT' },
  { name: '룩셈부르크', code: 'LU' },
  { name: '마카오', code: 'MO' },
  { name: '마케도니아', code: 'MK' },
  { name: '마다가스카르', code: 'MG' },
  { name: '말라위', code: 'MW' },
  { name: '말레이시아', code: 'MY' },
  { name: '몰디브', code: 'MV' },
  { name: '말리', code: 'ML' },
  { name: '몰타', code: 'MT' },
  { name: '마셜 제도', code: 'MH' },
  { name: '마르티니크', code: 'MQ' },
  { name: '모리타니', code: 'MR' },
  { name: '모리셔스', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: '멕시코', code: 'MX' },
  { name: '미크로네시아', code: 'FM' },
  { name: '몰도바', code: 'MD' },
  { name: '모나코', code: 'MC' },
  { name: '몽골리아', code: 'MN' },
  { name: '몬테네그로', code: 'ME' },
  { name: '몬세라트', code: 'MS' },
  { name: '모로코', code: 'MA' },
  { name: '모잠비크', code: 'MZ' },
  { name: '미얀마', code: 'MM' },
  { name: '나미비아', code: 'NA' },
  { name: '나우루', code: 'NR' },
  { name: '네팔', code: 'NP' },
  { name: '네덜란드', code: 'NL' },
  { name: '네덜란드 령 앤 틸리 스', code: 'AN' },
  { name: '뉴 칼레도니아', code: 'NC' },
  { name: '뉴질랜드', code: 'NZ' },
  { name: '니카라과', code: 'NI' },
  { name: '니제르', code: 'NE' },
  { name: '나이지리아', code: 'NG' },
  { name: '니우에', code: 'NU' },
  { name: '노퍽 섬', code: 'NF' },
  { name: '북마리아나 제도', code: 'MP' },
  { name: '노르웨이', code: 'NO' },
  { name: '오만', code: 'OM' },
  { name: '파키스탄', code: 'PK' },
  { name: '팔라우', code: 'PW' },
  { name: '팔레스타인 영토, 점령', code: 'PS' },
  { name: '파나마', code: 'PA' },
  { name: '파푸아 뉴기니', code: 'PG' },
  { name: '파라과이', code: 'PY' },
  { name: '페루', code: 'PE' },
  { name: '필리핀', code: 'PH' },
  { name: '핏케언', code: 'PN' },
  { name: '폴란드', code: 'PL' },
  { name: '포르투갈', code: 'PT' },
  { name: '푸에르토 리코', code: 'PR' },
  { name: '카타르', code: 'QA' },
  { name: '리유니온', code: 'RE' },
  { name: '루마니아', code: 'RO' },
  { name: '러시아', code: 'RU' },
  { name: '르완다', code: 'RW' },
  { name: '세인트 헬레나', code: 'SH' },
  { name: '세인트 키츠 네비스', code: 'KN' },
  { name: '세인트루시아', code: 'LC' },
  { name: '생 피에르와 미클롱', code: 'PM' },
  { name: '세인트 빈센트 그레나딘', code: 'VC' },
  { name: '사모아', code: 'WS' },
  { name: '산 마리노', code: 'SM' },
  { name: '상투메 프린시페', code: 'ST' },
  { name: '사우디 아라비아', code: 'SA' },
  { name: '세네갈', code: 'SN' },
  { name: '세르비아', code: 'RS' },
  { name: '세이셸', code: 'SC' },
  { name: '시에라리온', code: 'SL' },
  { name: '싱가포르', code: 'SG' },
  { name: '슬로바키아', code: 'SK' },
  { name: '슬로베니아', code: 'SI' },
  { name: '솔로몬 제도', code: 'SB' },
  { name: '소말리아', code: 'SO' },
  { name: '남아프리카', code: 'ZA' },
  { name: '사우스 조지아 및 사우스 샌드위치 제도', code: 'GS' },
  { name: '스페인', code: 'ES' },
  { name: '스리랑카', code: 'LK' },
  { name: '수단', code: 'SD' },
  { name: '수리남', code: 'SR' },
  { name: '스발바르와 얀 마옌', code: 'SJ' },
  { name: '스와질랜드', code: 'SZ' },
  { name: '스웨덴', code: 'SE' },
  { name: '스위스', code: 'CH' },
  { name: '시리아', code: 'SY' },
  { name: '대만', code: 'TW' },
  { name: '타지키스탄', code: 'TJ' },
  { name: '탄자니아', code: 'TZ' },
  { name: '태국', code: 'TH' },
  { name: '동티모르', code: 'TL' },
  { name: '토고', code: 'TG' },
  { name: '토켈라우', code: 'TK' },
  { name: '통가', code: 'TO' },
  { name: '트리니다드토바고', code: 'TT' },
  { name: '튀니지', code: 'TN' },
  { name: '터키', code: 'TR' },
  { name: '투르크메니스탄', code: 'TM' },
  { name: '터크스케이커스 제도', code: 'TC' },
  { name: '투발루', code: 'TV' },
  { name: '우간다', code: 'UG' },
  { name: '우크라이나', code: 'UA' },
  { name: '아랍 에미리트', code: 'AE' },
  { name: '영국', code: 'GB' },
  { name: '미국', code: 'US' },
  { name: '미국 작은 외딴 섬', code: 'UM' },
  { name: '우루과이', code: 'UY' },
  { name: '우즈베키스탄', code: 'UZ' },
  { name: '바누아투', code: 'VU' },
  { name: '베네수엘라', code: 'VE' },
  { name: '베트남', code: 'VN' },
  { name: '버진 아일랜드, 영국', code: 'VG' },
  { name: '미국령 버진아일랜드', code: 'VI' },
  { name: '월리스와 푸투나', code: 'WF' },
  { name: '서부 사하라', code: 'EH' },
  { name: '예멘', code: 'YE' },
  { name: '잠비아', code: 'ZM' },
  { name: '짐바브웨', code: 'ZW' },
];

export const CN_COUNTRY_LIST = [
  { name: '阿富汗', code: 'AF' },
  { name: '奥兰群岛', code: 'AX' },
  { name: '阿尔巴尼亚', code: 'AL' },
  { name: '阿尔及利亚', code: 'DZ' },
  { name: '美属萨摩亚', code: 'AS' },
  { name: '安道尔', code: 'AD' },
  { name: '安哥拉', code: 'AO' },
  { name: '安圭拉', code: 'AI' },
  { name: '南极洲', code: 'AQ' },
  { name: '安提瓜和巴布达', code: 'AG' },
  { name: '阿根廷', code: 'AR' },
  { name: '亚美尼亚', code: 'AM' },
  { name: '阿鲁巴岛', code: 'AW' },
  { name: '澳大利亚', code: 'AU' },
  { name: '奥地利', code: 'AT' },
  { name: '阿塞拜疆', code: 'AZ' },
  { name: '巴哈马', code: 'BS' },
  { name: '巴林', code: 'BH' },
  { name: '孟加拉国', code: 'BD' },
  { name: '巴巴多斯', code: 'BB' },
  { name: '白俄罗斯', code: 'BY' },
  { name: '比利时', code: 'BE' },
  { name: '伯利兹', code: 'BZ' },
  { name: '贝宁', code: 'BJ' },
  { name: '百慕大', code: 'BM' },
  { name: '不丹', code: 'BT' },
  { name: '玻利维亚', code: 'BO' },
  { name: '波斯尼亚和黑塞哥维那', code: 'BA' },
  { name: '博茨瓦纳', code: 'BW' },
  { name: '布维岛', code: 'BV' },
  { name: '巴西', code: 'BR' },
  { name: '英属印度洋领地', code: 'IO' },
  { name: '文莱达鲁萨兰国', code: 'BN' },
  { name: '保加利亚', code: 'BG' },
  { name: '布基纳法索', code: 'BF' },
  { name: '布隆迪', code: 'BI' },
  { name: '柬埔寨', code: 'KH' },
  { name: '喀麦隆', code: 'CM' },
  { name: '加拿大', code: 'CA' },
  { name: '佛得角', code: 'CV' },
  { name: '开曼群岛', code: 'KY' },
  { name: '中非共和国', code: 'CF' },
  { name: '乍得', code: 'TD' },
  { name: '智利', code: 'CL' },
  { name: '中国', code: 'CN' },
  { name: '圣诞岛', code: 'CX' },
  { name: '科科斯（基林）群岛', code: 'CC' },
  { name: '哥伦比亚', code: 'CO' },
  { name: '科摩罗', code: 'KM' },
  { name: '刚果', code: 'CG' },
  { name: '刚果民主共和国', code: 'CD' },
  { name: '库克群岛', code: 'CK' },
  { name: '哥斯达黎加', code: 'CR' },
  { name: '科特迪瓦', code: 'CI' },
  { name: '克罗地亚', code: 'HR' },
  { name: '古巴', code: 'CU' },
  { name: '塞浦路斯', code: 'CY' },
  { name: '捷克共和国', code: 'CZ' },
  { name: '丹麦', code: 'DK' },
  { name: '吉布提', code: 'DJ' },
  { name: '多米尼克', code: 'DM' },
  { name: '多明尼加共和国', code: 'DO' },
  { name: '厄瓜多尔', code: 'EC' },
  { name: '埃及', code: 'EG' },
  { name: '萨尔瓦多', code: 'SV' },
  { name: '赤道几内亚', code: 'GQ' },
  { name: '厄立特里亚', code: 'ER' },
  { name: '爱沙尼亚', code: 'EE' },
  { name: '埃塞俄比亚', code: 'ET' },
  { name: '福克兰群岛（马尔维纳斯）', code: 'FK' },
  { name: '法罗群岛', code: 'FO' },
  { name: '斐济', code: 'FJ' },
  { name: '芬兰', code: 'FI' },
  { name: '法国', code: 'FR' },
  { name: '法属圭亚那', code: 'GF' },
  { name: '法属波利尼西亚', code: 'PF' },
  { name: '法属南部领地', code: 'TF' },
  { name: '加蓬', code: 'GA' },
  { name: '冈比亚', code: 'GM' },
  { name: '乔治亚州', code: 'GE' },
  { name: '德国', code: 'DE' },
  { name: '加纳', code: 'GH' },
  { name: '直布罗陀', code: 'GI' },
  { name: '希腊', code: 'GR' },
  { name: '格陵兰', code: 'GL' },
  { name: '格林纳达', code: 'GD' },
  { name: '瓜德罗普', code: 'GP' },
  { name: '关岛', code: 'GU' },
  { name: '危地马拉', code: 'GT' },
  { name: '根西岛', code: 'GG' },
  { name: '几内亚', code: 'GN' },
  { name: '几内亚比绍', code: 'GW' },
  { name: '圭亚那', code: 'GY' },
  { name: '海地', code: 'HT' },
  { name: '赫德岛和麦当劳岛', code: 'HM' },
  { name: '圣座（梵蒂冈城邦）', code: 'VA' },
  { name: '洪都拉斯', code: 'HN' },
  { name: '香港', code: 'HK' },
  { name: '匈牙利', code: 'HU' },
  { name: '冰岛', code: 'IS' },
  { name: '印度', code: 'IN' },
  { name: '印度尼西亚', code: 'ID' },
  { name: '伊朗', code: 'IR' },
  { name: '伊拉克', code: 'IQ' },
  { name: '爱尔兰', code: 'IE' },
  { name: '马恩岛', code: 'IM' },
  { name: '以色列', code: 'IL' },
  { name: '意大利', code: 'IT' },
  { name: '牙买加', code: 'JM' },
  { name: '日本', code: 'JP' },
  { name: '球衣', code: 'JE' },
  { name: '约旦', code: 'JO' },
  { name: '哈萨克斯坦', code: 'KZ' },
  { name: '肯尼亚', code: 'KE' },
  { name: '基里巴斯', code: 'KI' },
  { name: '朝鲜民主主义人民共和国', code: 'KP' },
  { name: '大韩民国', code: 'KR' },
  { name: '科威特', code: 'KW' },
  { name: '吉尔吉斯斯坦', code: 'KG' },
  { name: '老挝人民民主共和国', code: 'LA' },
  { name: '拉脱维亚', code: 'LV' },
  { name: '黎巴嫩', code: 'LB' },
  { name: '莱索托', code: 'LS' },
  { name: '利比里亚', code: 'LR' },
  { name: '利比亚', code: 'LY' },
  { name: '列支敦士登', code: 'LI' },
  { name: '立陶宛', code: 'LT' },
  { name: '卢森堡', code: 'LU' },
  { name: '澳门', code: 'MO' },
  { name: '马其顿', code: 'MK' },
  { name: '马达加斯加', code: 'MG' },
  { name: '马拉维', code: 'MW' },
  { name: '马来西亚', code: 'MY' },
  { name: '马尔代夫', code: 'MV' },
  { name: '马里', code: 'ML' },
  { name: '马耳他', code: 'MT' },
  { name: '马绍尔群岛', code: 'MH' },
  { name: '马提尼克岛', code: 'MQ' },
  { name: '毛里塔尼亚', code: 'MR' },
  { name: '毛里求斯', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: '墨西哥', code: 'MX' },
  { name: '密克罗尼西亚', code: 'FM' },
  { name: '摩尔多瓦', code: 'MD' },
  { name: '摩纳哥', code: 'MC' },
  { name: '蒙古', code: 'MN' },
  { name: '黑山', code: 'ME' },
  { name: '蒙特塞拉特', code: 'MS' },
  { name: '摩洛哥', code: 'MA' },
  { name: '莫桑比克', code: 'MZ' },
  { name: '缅甸', code: 'MM' },
  { name: '纳米比亚', code: 'NA' },
  { name: '瑙鲁', code: 'NR' },
  { name: '尼泊尔', code: 'NP' },
  { name: '荷兰', code: 'NL' },
  { name: '荷属安的列斯', code: 'AN' },
  { name: '新喀里多尼亚', code: 'NC' },
  { name: '新西兰', code: 'NZ' },
  { name: '尼加拉瓜', code: 'NI' },
  { name: '尼日尔', code: 'NE' },
  { name: '尼日利亚', code: 'NG' },
  { name: '纽埃', code: 'NU' },
  { name: '诺福克岛', code: 'NF' },
  { name: '北马里亚纳群岛', code: 'MP' },
  { name: '挪威', code: 'NO' },
  { name: '阿曼', code: 'OM' },
  { name: '巴基斯坦', code: 'PK' },
  { name: '帕劳', code: 'PW' },
  { name: '巴勒斯坦领土，被占领', code: 'PS' },
  { name: '巴拿马', code: 'PA' },
  { name: '巴布亚新几内亚', code: 'PG' },
  { name: '巴拉圭', code: 'PY' },
  { name: '秘鲁', code: 'PE' },
  { name: '菲律宾', code: 'PH' },
  { name: '皮特凯恩', code: 'PN' },
  { name: '波兰', code: 'PL' },
  { name: '葡萄牙', code: 'PT' },
  { name: '波多黎各', code: 'PR' },
  { name: '卡塔尔', code: 'QA' },
  { name: '团圆', code: 'RE' },
  { name: '罗马尼亚', code: 'RO' },
  { name: '俄罗斯', code: 'RU' },
  { name: '卢旺达', code: 'RW' },
  { name: '圣赫勒拿', code: 'SH' },
  { name: '圣基茨和尼维斯', code: 'KN' },
  { name: '圣卢西亚', code: 'LC' },
  { name: '圣皮埃尔和密克隆', code: 'PM' },
  { name: '圣文森特和格林纳丁斯', code: 'VC' },
  { name: '萨摩亚', code: 'WS' },
  { name: '圣马力诺', code: 'SM' },
  { name: '圣多美和普林西比', code: 'ST' },
  { name: '沙特阿拉伯', code: 'SA' },
  { name: '塞内加尔', code: 'SN' },
  { name: '塞尔维亚', code: 'RS' },
  { name: '塞舌尔', code: 'SC' },
  { name: '塞拉利昂', code: 'SL' },
  { name: '新加坡', code: 'SG' },
  { name: '斯洛伐克', code: 'SK' },
  { name: '斯洛文尼亚', code: 'SI' },
  { name: '所罗门群岛', code: 'SB' },
  { name: '索马里', code: 'SO' },
  { name: '南非', code: 'ZA' },
  { name: '南乔治亚岛和南桑威奇群岛', code: 'GS' },
  { name: '西班牙', code: 'ES' },
  { name: '斯里兰卡', code: 'LK' },
  { name: '苏丹', code: 'SD' },
  { name: '苏里南', code: 'SR' },
  { name: '斯瓦尔巴和扬马延', code: 'SJ' },
  { name: '斯威士兰', code: 'SZ' },
  { name: '瑞典', code: 'SE' },
  { name: '瑞士', code: 'CH' },
  { name: '叙利亚', code: 'SY' },
  { name: '台湾', code: 'TW' },
  { name: '塔吉克斯坦', code: 'TJ' },
  { name: '坦桑尼亚', code: 'TZ' },
  { name: '泰国', code: 'TH' },
  { name: '东帝汶', code: 'TL' },
  { name: '多哥', code: 'TG' },
  { name: '托克劳', code: 'TK' },
  { name: '汤加', code: 'TO' },
  { name: '特立尼达和多巴哥', code: 'TT' },
  { name: '突尼斯', code: 'TN' },
  { name: '土耳其', code: 'TR' },
  { name: '土库曼斯坦', code: 'TM' },
  { name: '特克斯和凯科斯群岛', code: 'TC' },
  { name: '图瓦卢', code: 'TV' },
  { name: '乌干达', code: 'UG' },
  { name: '乌克兰', code: 'UA' },
  { name: '阿拉伯联合酋长国', code: 'AE' },
  { name: '英国', code: 'GB' },
  { name: '美国', code: 'US' },
  { name: '美国本土外小岛屿', code: 'UM' },
  { name: '乌拉圭', code: 'UY' },
  { name: '乌兹别克斯坦', code: 'UZ' },
  { name: '瓦努阿图', code: 'VU' },
  { name: '委内瑞拉', code: 'VE' },
  { name: '越南', code: 'VN' },
  { name: '英属维尔京群岛', code: 'VG' },
  { name: '美国维尔京群岛', code: 'VI' },
  { name: '瓦利斯和富图纳群岛', code: 'WF' },
  { name: '撒哈拉沙漠西部a', code: 'EH' },
  { name: '也门', code: 'YE' },
  { name: '赞比亚', code: 'ZM' },
  { name: '津巴布韦', code: 'ZW' },
];

export const COUNTRY_LIST =
  i18n?.language === 'kr'
    ? KR_COUNTRY_LIST
    : i18n?.language === 'cn'
    ? CN_COUNTRY_LIST
    : EN_COUNTRY_LIST;

export const PHONE_CODE =
  i18n?.language === 'kr'
    ? KR_PHONE_CODE
    : i18n?.language === 'cn'
    ? CN_PHONE_CODE
    : EN_PHONE_CODE;
